version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./src
    container_name: fast_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgresql://user:password@db/db
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./src
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./src:/app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
