version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./src
    container_name: fast_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/db
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
