name: App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./project/src

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --config=flake8/.flake8

    - name: Run tests
      run: |
        pytest ..
