name: App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./project/src

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Set PYTHONPATH for tests
      run: |
        echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pip install pytest
        pytest src/test_app.py  # Убедитесь, что тесты запускаются из правильной папки
